"""League metric definitions shared with the enterprise calculation model."""
TEAM_METRIC_CATEGORY = {'Attacks': ('contribution_impact', 'Attacks'),
 'Dangerous Attacks': ('contribution_impact', 'Dangerous Attacks'),
 'Ball Possession %': ('contribution_impact', 'Ball Possession %'),
 'Shots Total': ('shooting', 'Shots Total'),
 'Shots On Target': ('shooting', 'Shots On Target'),
 'Goals': ('shooting', 'Goals'),
 'Expected Goals (xG)': ('shooting', 'Expected Goals'),
 'Expected Goals on Target (xGoT)': ('shooting', 'Expected Goals On Target'),
 'Shooting Performance (SP)': ('shooting', 'Shooting Performance'),
 'Shots Insidebox': ('shooting', 'Shots Insidebox'),
 'Shots Outsidebox': ('shooting', 'Shots Outsidebox'),
 'Goal Attempts': ('shooting', 'Goal Attempts'),
 'Passes': ('passing', 'Passes'),
 'Successful Passes': ('passing', 'Accurate Passes'),
 'Successful Passes Percentage': ('passing', 'Accurate Passes (%)'),
 'Long Passes': ('passing', 'Long Balls'),
 'Successful Long Passes': ('passing', 'Long Balls Won'),
 'Successful Long Passes Percentage': ('passing', 'Long Balls Won (%)'),
 'Total Crosses': ('passing', 'Total Crosses'),
 'Accurate Crosses': ('passing', 'Accurate Crosses'),
 'Key Passes': ('passing', 'Key Passes'),
 'Corners': ('set_pieces', 'Corners'),
 'Goal Kicks': ('set_pieces', 'Goal Kicks'),
 'Free Kicks': ('set_pieces', 'Free Kicks'),
 'Throwins': ('set_pieces', 'Throwins'),
 'Penalties Scored': ('set_pieces', 'Penalties Scored'),
 'Penalties Missed': ('set_pieces', 'Penalties Missed'),
 'Penalties Won': ('set_pieces', 'Penalties Won'),
 'Penalties Committed': ('set_pieces', 'Penalties Committed'),
 'Penalties Saved': ('set_pieces', 'Penalties Saved'),
 'Big Chances Created': ('contribution_impact', 'Big Chances Created'),
 'Dribble Attempts': ('contribution_impact', 'Dribble Attempts'),
 'Successful Dribbles': ('contribution_impact', 'Successful Dribbles'),
 'Successful Dribbles Percentage': ('contribution_impact',
                                    'Dribble Accuracy (%)'),
 'Saves': ('defending', 'Saves'),
 'Tackles': ('defending', 'Tackles'),
 'Shots Blocked': ('defending', 'Blocked Shots'),
 'Interceptions': ('defending', 'Interceptions'),
 'Duels Won': ('defending', 'Duels Won'),
 'Successful Headers': ('defending', 'Successful Headers'),
 'Ball Safe': ('passing', 'Ball Safe'),
 'Shots Off Target': ('errors_discipline', 'Shots Off Target'),
 'Big Chances Missed': ('errors_discipline', 'Big Chances Missed'),
 'Fouls': ('errors_discipline', 'Fouls'),
 'Offsides': ('errors_discipline', 'Offsides'),
 'Yellowcards': ('errors_discipline', 'Yellow Cards'),
 'Redcards': ('errors_discipline', 'Red Cards')}

DERIVED_PERCENTAGE_METRICS = {'Shots On Target (%)': ('Shots On Target', 'Shots Total'),
 'Goal Conversion (%)': ('Goals', 'Shots Total'),
 'On Target Goal Conversion (%)': ('Goals', 'Shots On Target'),
 'Assist Efficiency (%)': ('Assists', 'Key Passes'),
 'Dribble Accuracy (%)': ('Successful Dribbles', 'Dribble Attempts'),
 'Tackles Won (%)': ('Tackles Won', 'Tackles'),
 'Aerials Won (%)': ('Aerials Won', 'Aerials'),
 'Duels Won (%)': ('Duels Won', 'Total Duels'),
 'Long Balls Won (%)': ('Long Balls Won', 'Long Balls'),
 'Accurate Passes (%)': ('Accurate Passes', 'Passes'),
 'Accurate Crosses (%)': ('Accurate Crosses', 'Total Crosses')}
